import { deleteCmsItem, saveCmsEvent, saveCmsNews, saveCmsPage } from "@/app/admin/cms/actions";
import { requireAdminPermission } from "@/lib/auth/require-role";

export const dynamic = "force-dynamic";
type SearchParams = Promise<{ notice?: string; error?: string }>;
type Item = { id: string; title: string; slug: string; status: string };
function Field({ name, label, required = true, type = "text" }: { name: string; label: string; required?: boolean; type?: string }) { return <label className="block text-sm font-semibold">{label}<input className="mt-1 min-h-11 w-full rounded border p-2" name={name} required={required} type={type} /></label>; }
function Area({ name, label }: { name: string; label: string }) { return <label className="block text-sm font-semibold">{label}<textarea className="mt-1 min-h-28 w-full rounded border p-2" name={name} /></label>; }
function Status() { return <label className="block text-sm font-semibold">Publication status<select className="mt-1 min-h-11 w-full rounded border bg-white p-2" defaultValue="draft" name="status"><option value="draft">Draft</option><option value="published">Published</option></select></label>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">{title}</h2>{children}</section>; }
function Listing({ kind, items }: { kind: "page" | "news" | "event"; items: Item[] }) { return <ul className="mt-4 space-y-2">{items.map((item) => <li className="flex flex-wrap items-center justify-between gap-2 rounded border p-3" key={item.id}><span><strong>{item.title}</strong> <span className="text-sm text-slate-600">/{item.slug} · {item.status}</span></span><form action={deleteCmsItem}><input name="id" type="hidden" value={item.id} /><input name="kind" type="hidden" value={kind} /><button className="min-h-10 rounded border border-red-700 px-3 text-sm font-semibold text-red-800" type="submit">Delete</button></form></li>)}</ul>; }

export default async function CmsAdminPage({ searchParams }: { searchParams: SearchParams }) {
  const supabase = await requireAdminPermission("website.manage");
  const [pages, news, events, message] = await Promise.all([supabase.from("cms_pages").select("id, title, slug, status").order("updated_at", { ascending: false }), supabase.from("cms_news_posts").select("id, title, slug, status").order("updated_at", { ascending: false }), supabase.from("public_events").select("id, title, slug, status").order("starts_at"), searchParams]);
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-8"><header><p className="font-semibold text-violet-700">Administrator CMS</p><h1 className="text-3xl font-bold">Public website content</h1><p className="mt-2 max-w-3xl">Create plain-text public content. Publish only approved information; this workspace does not upload images or collect contact, admissions, or academic facts.</p></header>{message.notice && <p className="rounded border border-green-300 bg-green-50 p-3" role="status">{message.notice.replaceAll("+", " ")}</p>}{message.error && <p className="rounded border border-red-300 bg-red-50 p-3" role="alert">{message.error}</p>}<div className="grid gap-6 lg:grid-cols-3"><Card title="Content page"><form action={saveCmsPage} className="mt-4 space-y-3"><Field label="Title" name="title" /><Field label="Slug" name="slug" /><Area label="Summary" name="summary" /><Area label="Plain-text body" name="body" /><Status /><button className="primary-cta min-h-11 rounded px-4 font-semibold" type="submit">Save page</button></form><Listing items={pages.data ?? []} kind="page" /></Card><Card title="News post"><form action={saveCmsNews} className="mt-4 space-y-3"><Field label="Title" name="title" /><Field label="Slug" name="slug" /><Area label="Excerpt" name="excerpt" /><Area label="Plain-text body" name="body" /><Status /><button className="primary-cta min-h-11 rounded px-4 font-semibold" type="submit">Save news</button></form><Listing items={news.data ?? []} kind="news" /></Card><Card title="Public event"><form action={saveCmsEvent} className="mt-4 space-y-3"><Field label="Title" name="title" /><Field label="Slug" name="slug" /><Area label="Summary" name="summary" /><Area label="Plain-text details" name="details" /><Field label="Starts at (ISO date/time with timezone)" name="starts_at" /><Field label="Ends at (ISO date/time with timezone)" name="ends_at" /><Status /><button className="primary-cta min-h-11 rounded px-4 font-semibold" type="submit">Save event</button></form><Listing items={events.data ?? []} kind="event" /></Card></div></main>;
}
