import Link from "next/link";
import { PortalHeader } from "@/components/dashboard-ui";
import { createCmsReplacementDraft, deleteCmsItem, publishCmsItem, saveCmsEvent, saveCmsNews, saveCmsPage } from "@/app/admin/cms/actions";
import { requireWebsiteContentEditor } from "@/lib/auth/require-role";

export const dynamic = "force-dynamic";
type Kind = "page" | "news" | "event";
type SearchParams = Promise<{ notice?: string; error?: string; edit?: string; kind?: Kind }>;
type Item = { id: string; title: string; slug: string; status: string; version: number; image_path?: string | null; summary?: string; body?: string; excerpt?: string; details?: string; starts_at?: string; ends_at?: string };
const input = "mt-1 min-h-11 w-full rounded border-2 border-slate-700 bg-white p-2 text-slate-950";
function Field({ name, label, value = "", type = "text" }: { name: string; label: string; value?: string; type?: string }) { return <label className="block text-sm font-semibold text-slate-950">{label}<input className={input} name={name} required type={type} defaultValue={value} /></label>; }
function Area({ name, label, value = "" }: { name: string; label: string; value?: string }) { return <label className="block text-sm font-semibold text-slate-950">{label}<textarea className={`${input} min-h-28`} name={name} defaultValue={value} /></label>; }
function ImageFields({ item }: { item?: Item }) { return <fieldset className="rounded border border-slate-300 p-3"><legend className="px-1 text-sm font-semibold">Image (optional)</legend><label className="block text-sm font-medium">Upload image<input accept="image/jpeg,image/png,image/webp" className="mt-1 block w-full text-sm" name="image" type="file" /></label><p className="mt-1 text-sm text-slate-700">JPEG, PNG, or WebP; maximum 5 MB. Images are private until their content is published.</p>{item?.image_path && <label className="mt-2 flex items-center gap-2 text-sm font-medium"><input name="remove_image" type="checkbox" /> Remove current image</label>}</fieldset>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border-2 border-slate-800 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-950">{title}</h2>{children}</section>; }
function Listing({ kind, items, canPublish, canDelete }: { kind: Kind; items: Item[]; canPublish: boolean; canDelete: boolean }) { return <ul className="mt-4 space-y-2">{items.map((item) => <li className="flex flex-wrap items-center justify-between gap-2 rounded border-2 border-slate-300 p-3" key={item.id}><span><strong>{item.title}</strong> <span className="text-sm text-slate-700">/{item.slug} · {item.status} · v{item.version}{item.image_path ? " · image" : ""}</span></span><span className="flex gap-2">{item.status === "draft" && <Link className="min-h-10 rounded border-2 border-violet-800 px-3 py-2 text-sm font-bold text-violet-950" href={`/admin/cms?kind=${kind}&edit=${item.id}`}>Edit draft</Link>}{item.status === "published" && <form action={createCmsReplacementDraft}><input name="id" type="hidden" value={item.id} /><input name="kind" type="hidden" value={kind} /><button className="min-h-10 rounded border-2 border-violet-800 px-3 py-2 text-sm font-bold text-violet-950" type="submit">Create replacement draft</button></form>}{item.status === "draft" && canPublish && <form action={publishCmsItem}><input name="id" type="hidden" value={item.id} /><input name="kind" type="hidden" value={kind} /><button className="min-h-10 rounded bg-slate-950 px-3 text-sm font-bold text-white" type="submit">Publish replacement</button></form>}{item.status === "draft" && canDelete && <form action={deleteCmsItem}><input name="id" type="hidden" value={item.id} /><input name="kind" type="hidden" value={kind} /><button className="min-h-10 rounded border-2 border-red-800 px-3 text-sm font-bold text-red-900" type="submit">Delete my draft</button></form>}</span></li>)}</ul>; }
function CmsForm({ kind, item, action }: { kind: Kind; item?: Item; action: (formData: FormData) => Promise<void> }) { const summary = kind === "news" ? "Excerpt" : "Summary"; const detail = kind === "event" ? "Plain-text details" : "Plain-text body"; return <form action={action} className="mt-4 space-y-3" encType="multipart/form-data">{item && <input name="id" type="hidden" value={item.id} />}<input name="status" type="hidden" value="draft" />{kind === "news" && <input name="published_at" type="hidden" value="" />}<Field label="Title" name="title" value={item?.title} /><Field label="Slug" name="slug" value={item?.slug} />{kind === "news" ? <Area label={summary} name="excerpt" value={item?.excerpt} /> : <Area label={summary} name="summary" value={item?.summary} />}{kind === "event" && <><Field label="Starts at" name="starts_at" type="datetime-local" value={item?.starts_at?.slice(0, 16)} /><Field label="Ends at" name="ends_at" type="datetime-local" value={item?.ends_at?.slice(0, 16)} /></>}<Area label={detail} name={kind === "event" ? "details" : "body"} value={kind === "event" ? item?.details : item?.body} /><ImageFields item={item} /><button className="primary-cta min-h-11 rounded px-4 font-bold" type="submit">{item ? `Save ${kind} draft` : `Create ${kind} draft`}</button></form>; }

export default async function CmsAdminPage({ searchParams }: { searchParams: SearchParams }) {
  const supabase = await requireWebsiteContentEditor();
  const [pages, news, events, permission, isAdminEditor, message] = await Promise.all([
    supabase.from("cms_pages").select("id,title,slug,status,version,summary,body,image_path").order("updated_at", { ascending: false }),
    supabase.from("cms_news_posts").select("id,title,slug,status,version,excerpt,body,image_path").order("updated_at", { ascending: false }),
    supabase.from("public_events").select("id,title,slug,status,version,summary,details,starts_at,ends_at,image_path").order("starts_at"),
    supabase.rpc("has_admin_permission", { required_permission: "website_content.publish" }).then(({ data }) => data === true),
    supabase.rpc("has_admin_permission", { required_permission: "website_content.edit" }).then(({ data }) => data === true), searchParams,
  ]);
  const all = { page: pages.data ?? [], news: news.data ?? [], event: events.data ?? [] } as Record<Kind, Item[]>;
  const selected = message.edit && message.kind ? all[message.kind].find((item) => item.id === message.edit) : undefined;
  const editingKind = selected && message.kind;
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-8"><PortalHeader role="admin" eyebrow="Website content workspace" title="Draft, review, and publish"><p>Editors can create and change drafts. Only authorized administrator positions can publish. Published records are locked; make a new draft for a future replacement.</p></PortalHeader>{message.notice && <p className="rounded border-2 border-green-800 bg-green-50 p-3 font-semibold text-slate-950" role="status">{message.notice.replaceAll("+", " ")}</p>}{message.error && <p className="rounded border-2 border-red-800 bg-red-50 p-3 font-semibold text-slate-950" role="alert">{message.error}</p>}<div className="grid gap-6 lg:grid-cols-3"><Card title="Content page">{(!editingKind || editingKind === "page") && <CmsForm action={saveCmsPage} item={selected} kind="page" />}<Listing items={all.page} kind="page" canPublish={permission} canDelete={!isAdminEditor} /></Card><Card title="News post">{(!editingKind || editingKind === "news") && <CmsForm action={saveCmsNews} item={selected} kind="news" />}<Listing items={all.news} kind="news" canPublish={permission} canDelete={!isAdminEditor} /></Card><Card title="Public event">{(!editingKind || editingKind === "event") && <CmsForm action={saveCmsEvent} item={selected} kind="event" />}<Listing items={all.event} kind="event" canPublish={permission} canDelete={!isAdminEditor} /></Card></div></main>;
}
