"use client";

import { useActionState } from "react";
import { changeAdministratorPosition, createAccount, type AccountActionState, deprovisionAccount, retryPendingAuthBan } from "@/app/admin/account-actions";

const initialState: AccountActionState = {};
type Account = { id: string; email: string; role: string | null; position: string | null; active: boolean; authBanState: string | null; isProprietor: boolean };
type AuthorizationEvent = { id: string; occurredAt: string; actor: string; subject: string; eventType: string; position: string | null; role: string | null };

export function AccountManager({ accounts, events }: { accounts: Account[]; events: AuthorizationEvent[] }) {
  const [state, formAction, pending] = useActionState(createAccount, initialState);
  const activeAdmins = accounts.filter((account) => account.active && account.role === "admin");
  return <div className="space-y-8">
    <section className="rounded-lg border bg-white p-5 shadow-sm">
      <h2 className="text-xl font-bold">Create account</h2>
      <p className="mt-1 text-sm text-slate-700">No invitation email is sent. Copy the generated temporary password and deliver it only to Marshall through the approved secure channel.</p>
      <form action={formAction} className="mt-4 grid gap-3 md:grid-cols-2">
        <label className="text-sm font-medium">Email<input name="email" type="email" required maxLength={254} className="mt-1 min-h-11 w-full rounded border p-2" /></label>
        <label className="text-sm font-medium">Portal role<select name="role" required defaultValue="" className="mt-1 min-h-11 w-full rounded border bg-white p-2"><option value="" disabled>Select…</option><option value="admin">Administrator</option><option value="teacher">Teacher</option><option value="parent">Parent</option><option value="student">Student</option></select></label>
        <label className="text-sm font-medium">Administrator position<select name="position" defaultValue="" className="mt-1 min-h-11 w-full rounded border bg-white p-2"><option value="">Not applicable</option><option value="senior_administrator">Senior administrator</option><option value="headmistress">Headmistress</option></select></label>
        <div className="flex items-end"><button disabled={pending} className="min-h-11 rounded bg-violet-700 px-4 py-2 font-semibold text-white disabled:opacity-60">{pending ? "Creating…" : "Create account"}</button></div>
      </form>
      {state.error && <p className="mt-3 rounded border border-red-300 bg-red-50 p-3" role="alert">{state.error}</p>}
      {state.temporaryPassword && <div className="mt-3 rounded border border-amber-300 bg-amber-50 p-3" role="status"><strong>Temporary password for {state.email}:</strong> <code className="break-all">{state.temporaryPassword}</code><p className="mt-1 text-sm">Shown only for this response. Do not put it in email, logs, or school records.</p></div>}
    </section>
    <section className="rounded-lg border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Accounts</h2><p className="mt-1 text-sm text-slate-700">“Deprovision” immediately removes database authorization and preserves linked records. It is complete only after the Auth ban succeeds; a failed ban remains visible here for proprietor retry.</p>
      <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Email</th><th className="p-2">Role</th><th className="p-2">Position</th><th className="p-2">Status</th><th className="p-2">Action</th></tr></thead><tbody>{accounts.map((account) => <tr className="border-b" key={account.id}><td className="p-2">{account.email}</td><td className="p-2">{account.role ?? "Unassigned"}</td><td className="p-2">{account.position ?? "—"}</td><td className="p-2">{account.active ? "Active" : account.authBanState === "succeeded" ? "Deprovisioned" : "Deprovisioned — Auth ban retry required"}</td><td className="p-2">{account.active ? <form action={deprovisionAccount}><input type="hidden" name="userId" value={account.id} /><button className="rounded border border-red-600 px-3 py-1 text-red-700" type="submit">Deprovision</button></form> : account.authBanState !== "succeeded" ? <form action={retryPendingAuthBan}><input type="hidden" name="userId" value={account.id} /><button className="rounded border border-amber-600 px-3 py-1 text-amber-800" type="submit">Retry Auth ban</button></form> : null}</td></tr>)}</tbody></table></div>
    </section>
    <section className="rounded-lg border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Administrator positions</h2><p className="mt-1 text-sm text-slate-700">Only active existing administrator accounts can receive Tier 2 or Tier 3. Proprietor, self, and higher-position changes are refused by the server and database capability.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Administrator</th><th className="p-2">Current position</th><th className="p-2">Change</th></tr></thead><tbody>{activeAdmins.map((account) => <tr className="border-b" key={account.id}><td className="p-2">{account.email}</td><td className="p-2">{account.position ?? "No active position"}</td><td className="p-2">{account.isProprietor ? <span className="text-slate-600">Bootstrap-only proprietor</span> : <form action={changeAdministratorPosition} className="flex gap-2"><input type="hidden" name="userId" value={account.id} /><select name="position" defaultValue={account.position ?? ""} className="rounded border bg-white p-1"><option value="">Revoke position</option><option value="senior_administrator">Senior administrator (Tier 2)</option><option value="headmistress">Headmistress (Tier 3)</option></select><button className="rounded border border-violet-700 px-3 py-1 text-violet-800" type="submit">Save</button></form>}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-lg border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Authorization audit</h2><p className="mt-1 text-sm text-slate-700">Most recent 100 authorization and lifecycle events. This is read-only.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">When</th><th className="p-2">Event</th><th className="p-2">Actor</th><th className="p-2">Subject</th><th className="p-2">Detail</th></tr></thead><tbody>{events.map((event) => <tr className="border-b" key={event.id}><td className="p-2">{new Date(event.occurredAt).toLocaleString()}</td><td className="p-2">{event.eventType}</td><td className="p-2">{event.actor}</td><td className="p-2">{event.subject}</td><td className="p-2">{event.position ?? event.role ?? "—"}</td></tr>)}{events.length === 0 && <tr><td className="p-2 text-slate-600" colSpan={5}>No authorization events yet.</td></tr>}</tbody></table></div></section>
  </div>;
}
