import { saveEvent } from "@/app/communications-actions";
import { AudienceLabels, AudienceOptions, Notice } from "@/components/audience-ui";
import { EmptyDashboardState, PortalHeader, UnavailableDashboardState } from "@/components/dashboard-ui";
import { requireAdminPermission } from "@/lib/auth/require-role";

export const dynamic = "force-dynamic";
type SearchParams = Promise<{ notice?: string; error?: string }>;
type Target = { target_kind: string; role_code: string | null; class_group_id: string | null };
function localInput(value: string) { return value.slice(0, 16); }
function audienceValue(target: Target) { return target.target_kind === "school" ? "school" : target.target_kind === "role" ? `role:${target.role_code}` : `class:${target.class_group_id}`; }

export default async function CalendarManagementPage({ searchParams }: { searchParams: SearchParams }) {
  const supabase = await requireAdminPermission("calendar.manage");
  const [{ data: classes, error: classError }, { data: events, error }, params] = await Promise.all([
    supabase.from("class_groups").select("id,name,level").order("name"),
    supabase.from("events").select("id,title,description,starts_at,ends_at,status,event_targets(target_kind,role_code,class_group_id)").order("starts_at").limit(100), searchParams,
  ]);
  if (classError || error) return <main className="mx-auto max-w-6xl space-y-6"><PortalHeader role="admin" eyebrow="Calendar" title="Private events"><p>The management queue could not be loaded.</p></PortalHeader><UnavailableDashboardState /></main>;
  const classRows = classes ?? [];
  return <main className="mx-auto max-w-6xl space-y-6"><PortalHeader role="admin" eyebrow="Calendar" title="Private school events"><p>Drafts may be edited or published. Published events may only be cancelled; cancelled records are terminal. All mutations require <code>calendar.manage</code>.</p></PortalHeader><Notice {...params} /><section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-lg font-bold">New private event</h2><EventForm classes={classRows} /></section>{events?.length ? <section className="space-y-4" aria-label="Calendar management queue">{events.map((item) => <details key={item.id} className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><summary className="cursor-pointer font-bold">{item.title} <span className="ml-2 text-sm font-normal capitalize text-slate-700">{item.status}</span></summary><div className="mt-4 space-y-3"><p className="text-sm text-slate-700">{new Date(item.starts_at).toLocaleString()} – {new Date(item.ends_at).toLocaleString()}</p><AudienceLabels classes={classRows} targets={(item.event_targets ?? []) as Target[]} /><EventForm item={{ ...item, event_targets: (item.event_targets ?? []) as Target[] }} classes={classRows} /></div></details>)}</section> : <EmptyDashboardState title="No private events yet">Create a draft when an approved school date is ready.</EmptyDashboardState>}</main>;
}
function EventForm({ classes, item }: { classes: { id: string; name: string; level: string }[]; item?: { id: string; title: string; description: string; starts_at: string; ends_at: string; status: string; event_targets: Target[] } }) {
  if (item?.status === "published") return <form action={saveEvent} className="mt-4"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="title" value={item.title} /><input type="hidden" name="description" value={item.description} /><input type="hidden" name="starts_at" value={localInput(item.starts_at)} /><input type="hidden" name="ends_at" value={localInput(item.ends_at)} />{item.event_targets.map((target, index) => <input key={index} type="hidden" name="audiences" value={audienceValue(target)} />)}<input type="hidden" name="intent" value="cancel" /><button className="min-h-11 rounded bg-slate-700 px-4 py-3 font-semibold text-white" type="submit">Cancel event</button></form>;
  if (item?.status === "cancelled") return <p className="text-sm text-slate-700">Cancelled events are terminal and cannot be changed.</p>;
  return <form action={saveEvent} className="mt-4 space-y-4"><input name="id" type="hidden" value={item?.id ?? ""} /><label className="block font-semibold">Title<input className="mt-1 min-h-11 w-full rounded border p-3" name="title" maxLength={200} required defaultValue={item?.title ?? ""} /></label><label className="block font-semibold">Description<textarea className="mt-1 min-h-28 w-full rounded border p-3" name="description" maxLength={10000} defaultValue={item?.description ?? ""} /></label><p className="text-sm text-slate-700">The date and time fields are interpreted and stored as UTC (not your browser’s local timezone). These records are private and never publish to the public website.</p><div className="grid gap-3 sm:grid-cols-2"><label className="block font-semibold">Starts (UTC)<input className="mt-1 min-h-11 w-full rounded border p-3" type="datetime-local" name="starts_at" required defaultValue={item ? localInput(item.starts_at) : ""} /></label><label className="block font-semibold">Ends (UTC)<input className="mt-1 min-h-11 w-full rounded border p-3" type="datetime-local" name="ends_at" required defaultValue={item ? localInput(item.ends_at) : ""} /></label></div><AudienceOptions classes={classes} selected={item?.event_targets} /><label className="block font-semibold">Action<select className="mt-1 min-h-11 w-full rounded border bg-white p-3" name="intent" defaultValue="draft"><option value="draft">Save draft</option>{item && <option value="publish">Publish internally</option>}</select></label><button className="primary-cta min-h-11 rounded px-4 py-3 font-semibold" type="submit">{item ? "Save event" : "Create draft"}</button></form>;
}
