import { correctAttendanceRecord } from "@/app/operations-actions";
import { EmptyDashboardState, PortalHeader, UnavailableDashboardState } from "@/components/dashboard-ui";
import { requireAdminPermission } from "@/lib/auth/require-role";

export const dynamic = "force-dynamic";
type SearchParams = Promise<{ status?: string; notice?: string; error?: string }>;

export default async function AttendanceOperationsPage({ searchParams }: { searchParams: SearchParams }) {
  const supabase = await requireAdminPermission("attendance.review");
  const params = await searchParams;
  const sessionsQuery = supabase.from("attendance_sessions").select("id, attendance_date, session_number, status, student_visible, class_groups(name, level), attendance_records(student_id, status, students(first_name, last_name, admission_number))").order("attendance_date", { ascending: false }).limit(50);
  if (["draft", "submitted", "corrected"].includes(params.status ?? "")) sessionsQuery.eq("status", params.status!);
  const { data: sessions, error } = await sessionsQuery;
  if (error) return <main className="mx-auto max-w-6xl space-y-6"><PortalHeader eyebrow="Operations" title="Attendance review"><p>The attendance review queue could not be loaded.</p></PortalHeader><UnavailableDashboardState /></main>;
  return <main className="mx-auto max-w-6xl space-y-6"><PortalHeader eyebrow="Administrator operations" title="Attendance review"><p>Review submitted or corrected registers. Corrections are performed only through the attendance.review permission and are recorded as corrected.</p></PortalHeader>{params.notice && <p role="status" className="rounded border border-green-300 bg-green-50 p-3">{params.notice.replaceAll("+", " ")}</p>}{params.error && <p role="alert" className="rounded border border-red-300 bg-red-50 p-3">{params.error}</p>}<form className="flex gap-2" method="get"><label className="text-sm font-medium">Status<select className="ml-2 min-h-11 rounded border p-2" name="status" defaultValue={params.status ?? ""}><option value="">All</option><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="corrected">Corrected</option></select></label><button className="min-h-11 rounded border px-4 font-semibold" type="submit">Filter</button></form>{sessions?.length ? <div className="space-y-4">{sessions.map((session) => { const group = Array.isArray(session.class_groups) ? session.class_groups[0] : session.class_groups; return <section key={session.id} className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">{group?.level}: {group?.name} · {session.attendance_date} · Session {session.session_number}</h2><p className="mt-1 text-sm text-slate-700">Status: <span className="font-semibold capitalize">{session.status}</span> · Student visibility: {session.student_visible ? "enabled" : "disabled"}</p><div className="mt-4 space-y-3">{session.attendance_records.map((record) => { const student = Array.isArray(record.students) ? record.students[0] : record.students; return <form action={correctAttendanceRecord} key={record.student_id} className="grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-[1fr_auto_auto_auto]"><input type="hidden" name="attendance_session_id" value={session.id} /><input type="hidden" name="student_id" value={record.student_id} /><p className="self-center text-sm font-medium">{student?.first_name} {student?.last_name} <span className="text-slate-600">{student?.admission_number}</span></p><label className="text-sm">Status<select name="status" defaultValue={record.status} className="mt-1 min-h-11 rounded border p-2"><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select></label><label className="self-center text-sm"><input name="student_visible" type="checkbox" defaultChecked={session.student_visible} /> visible to student</label><button className="min-h-11 rounded border px-3 font-semibold" type="submit">Correct</button></form>; })}</div></section>; })}</div> : <EmptyDashboardState title="No attendance sessions">No registers match this filter.</EmptyDashboardState>}</main>;
}
