-- Phase 3 RLS is deny-by-default. Administrative policies are permission-specific;
-- no policy relies on broad admin-role membership.
create function app_private.enforce_results_release() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status = 'released' and old.status is distinct from 'released' and not app_private.has_admin_permission('results.release') then
    raise exception 'results.release permission is required to release results' using errcode = '42501';
  end if;
  return new;
end;
$$;
revoke all on function app_private.enforce_results_release() from public, anon, authenticated;
create trigger assessments_release_permission before update of status on public.assessments for each row execute procedure app_private.enforce_results_release();

grant select, insert, update, delete on public.timetable_entries, public.attendance_sessions, public.attendance_records, public.assignments, public.assessments, public.assessment_results, public.announcements, public.announcement_targets, public.events, public.event_targets, public.documents, public.document_targets, public.assignment_documents, public.operational_events to authenticated;

alter table public.timetable_entries enable row level security; alter table public.attendance_sessions enable row level security; alter table public.attendance_records enable row level security; alter table public.assignments enable row level security; alter table public.assessments enable row level security; alter table public.assessment_results enable row level security; alter table public.announcements enable row level security; alter table public.announcement_targets enable row level security; alter table public.events enable row level security; alter table public.event_targets enable row level security; alter table public.documents enable row level security; alter table public.document_targets enable row level security; alter table public.assignment_documents enable row level security; alter table public.operational_events enable row level security;

create policy timetable_admin on public.timetable_entries for all to authenticated using (app_private.has_admin_permission('timetable.manage')) with check (app_private.has_admin_permission('timetable.manage'));
create policy timetable_teacher_read on public.timetable_entries for select to authenticated using (app_private.is_active_teacher_assignment(class_group_id,subject_id,term_id));

create policy attendance_admin on public.attendance_sessions for all to authenticated using (app_private.has_admin_permission('attendance.review')) with check (app_private.has_admin_permission('attendance.review'));
create policy attendance_teacher_read on public.attendance_sessions for select to authenticated using (app_private.is_active_teacher_for_class(class_group_id));
create policy attendance_teacher_insert_draft on public.attendance_sessions for insert to authenticated with check (status='draft' and not student_visible and app_private.is_active_teacher_for_class(class_group_id));
create policy attendance_teacher_update_draft on public.attendance_sessions for update to authenticated using (status='draft' and app_private.is_active_teacher_for_class(class_group_id)) with check (status='draft' and not student_visible and app_private.is_active_teacher_for_class(class_group_id));
create policy attendance_parent_student_read on public.attendance_sessions for select to authenticated using (status in ('submitted','corrected') and exists(select 1 from public.attendance_records ar where ar.attendance_session_id=id and (app_private.is_active_guardian_of(ar.student_id) or (student_visible and app_private.is_active_student_self(ar.student_id)))));
create policy attendance_records_admin on public.attendance_records for all to authenticated using (app_private.has_admin_permission('attendance.review')) with check (app_private.has_admin_permission('attendance.review'));
create policy attendance_records_teacher_read on public.attendance_records for select to authenticated using (exists(select 1 from public.attendance_sessions s where s.id=attendance_session_id and app_private.is_active_teacher_for_class(s.class_group_id)));
create policy attendance_records_teacher_draft_write on public.attendance_records for insert to authenticated with check (exists(select 1 from public.attendance_sessions s where s.id=attendance_session_id and s.status='draft' and app_private.is_active_teacher_for_class(s.class_group_id)));
create policy attendance_records_teacher_draft_update on public.attendance_records for update to authenticated using (exists(select 1 from public.attendance_sessions s where s.id=attendance_session_id and s.status='draft' and app_private.is_active_teacher_for_class(s.class_group_id))) with check (exists(select 1 from public.attendance_sessions s where s.id=attendance_session_id and s.status='draft' and app_private.is_active_teacher_for_class(s.class_group_id)));
create policy attendance_records_family_read on public.attendance_records for select to authenticated using (exists(select 1 from public.attendance_sessions s where s.id=attendance_session_id and s.status in ('submitted','corrected') and (app_private.is_active_guardian_of(student_id) or (s.student_visible and app_private.is_active_student_self(student_id)))));

create policy assignments_admin on public.assignments for all to authenticated using (app_private.has_admin_permission('assessments.review')) with check (app_private.has_admin_permission('assessments.review'));
create policy assignments_teacher_all on public.assignments for all to authenticated using (app_private.is_active_teacher_assignment((select ta.class_group_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),(select ta.subject_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),term_id) and status='draft') with check (app_private.is_active_teacher_assignment((select ta.class_group_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),(select ta.subject_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),term_id) and status='draft');
create policy assignments_family_read on public.assignments for select to authenticated using (status='published' and exists(select 1 from public.teacher_assignments ta join public.class_enrolments ce on ce.class_group_id=ta.class_group_id where ta.id=teacher_assignment_id and ce.status='active' and ce.starts_on<=current_date and (ce.ends_on is null or ce.ends_on>=current_date) and (app_private.is_active_student_self(ce.student_id) or app_private.is_active_guardian_of(ce.student_id))));

create policy assessments_admin on public.assessments for all to authenticated using (app_private.has_admin_permission('assessments.review')) with check (app_private.has_admin_permission('assessments.review'));
create policy assessments_teacher_draft on public.assessments for all to authenticated using (status='draft' and app_private.is_active_teacher_assignment((select ta.class_group_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),(select ta.subject_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),term_id)) with check (status='draft' and app_private.is_active_teacher_assignment((select ta.class_group_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),(select ta.subject_id from public.teacher_assignments ta where ta.id=teacher_assignment_id),term_id));
create policy assessment_results_admin on public.assessment_results for all to authenticated using (app_private.has_admin_permission('assessments.review')) with check (app_private.has_admin_permission('assessments.review'));
create policy assessment_results_teacher_draft on public.assessment_results for all to authenticated using (exists(select 1 from public.assessments a join public.teacher_assignments ta on ta.id=a.teacher_assignment_id where a.id=assessment_id and a.status='draft' and app_private.is_active_teacher_assignment(ta.class_group_id,ta.subject_id,a.term_id))) with check (exists(select 1 from public.assessments a join public.teacher_assignments ta on ta.id=a.teacher_assignment_id where a.id=assessment_id and a.status='draft' and app_private.is_active_teacher_assignment(ta.class_group_id,ta.subject_id,a.term_id)));
create policy assessment_results_family_released on public.assessment_results for select to authenticated using (exists(select 1 from public.assessments a where a.id=assessment_id and a.status='released') and (app_private.is_active_student_self(student_id) or app_private.is_active_guardian_of(student_id)));
-- Release is deliberately separate: only active proprietor/senior mappings carry results.release.
create policy assessments_release on public.assessments for update to authenticated using (app_private.has_admin_permission('results.release')) with check (app_private.has_admin_permission('results.release'));

create policy announcements_admin on public.announcements for all to authenticated using (app_private.has_admin_permission('communications.manage')) with check (app_private.has_admin_permission('communications.manage'));
create policy announcement_targets_admin on public.announcement_targets for all to authenticated using (app_private.has_admin_permission('communications.manage')) with check (app_private.has_admin_permission('communications.manage'));
create policy announcements_audience_read on public.announcements for select to authenticated using (status='published' and exists(select 1 from public.announcement_targets t where t.announcement_id=id and app_private.matches_audience(t.target_kind,t.role_code,t.class_group_id)));
create policy announcement_targets_audience_read on public.announcement_targets for select to authenticated using (exists(select 1 from public.announcements a where a.id=announcement_id and a.status='published') and app_private.matches_audience(target_kind,role_code,class_group_id));
create policy events_admin on public.events for all to authenticated using (app_private.has_admin_permission('calendar.manage')) with check (app_private.has_admin_permission('calendar.manage'));
create policy event_targets_admin on public.event_targets for all to authenticated using (app_private.has_admin_permission('calendar.manage')) with check (app_private.has_admin_permission('calendar.manage'));
create policy events_audience_read on public.events for select to authenticated using (status='published' and is_public=false and exists(select 1 from public.event_targets t where t.event_id=id and app_private.matches_audience(t.target_kind,t.role_code,t.class_group_id)));
create policy event_targets_audience_read on public.event_targets for select to authenticated using (exists(select 1 from public.events e where e.id=event_id and e.status='published' and e.is_public=false) and app_private.matches_audience(target_kind,role_code,class_group_id));

create policy documents_admin on public.documents for all to authenticated using (app_private.has_admin_permission('documents.manage')) with check (app_private.has_admin_permission('documents.manage'));
create policy document_targets_admin on public.document_targets for all to authenticated using (app_private.has_admin_permission('documents.manage')) with check (app_private.has_admin_permission('documents.manage'));
create policy documents_available_read on public.documents for select to authenticated using (status='available' and app_private.can_access_document(id));
create policy document_targets_available_read on public.document_targets for select to authenticated using (exists(select 1 from public.documents d where d.id=document_id and d.status='available') and app_private.matches_audience(target_kind,role_code,class_group_id));
create policy assignment_documents_admin on public.assignment_documents for all to authenticated using (app_private.has_admin_permission('assessments.review')) with check (app_private.has_admin_permission('assessments.review'));
create policy assignment_documents_teacher_draft on public.assignment_documents for all to authenticated using (exists(select 1 from public.assignments a join public.teacher_assignments ta on ta.id=a.teacher_assignment_id where a.id=assignment_id and a.status='draft' and app_private.is_active_teacher_assignment(ta.class_group_id,ta.subject_id,a.term_id))) with check (exists(select 1 from public.assignments a join public.teacher_assignments ta on ta.id=a.teacher_assignment_id where a.id=assignment_id and a.status='draft' and app_private.is_active_teacher_assignment(ta.class_group_id,ta.subject_id,a.term_id)));
create policy assignment_documents_family_read on public.assignment_documents for select to authenticated using (exists(select 1 from public.assignments a where a.id=assignment_id and a.status='published') and app_private.can_access_document(document_id));
create policy operational_events_admin_read on public.operational_events for select to authenticated using (app_private.has_admin_permission('attendance.review') or app_private.has_admin_permission('assessments.review') or app_private.has_admin_permission('documents.manage'));

-- Metadata authorizes every future object transfer. The bucket is private and there
-- are intentionally no storage.objects browser policies: a later server-only
-- transfer/signing implementation must verify can_access_document(document id)
-- and enforce storage.objects.name = documents/<document UUID> before upload/download.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('school-documents','school-documents',false,10485760,array['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg']) on conflict (id) do update set public=false,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;
